spring:
  profiles: production
  datasource:
    url:  jdbc:mysql://localhost:3306/api_db
    username: root
    driverClassName: com.mysql.cj.jdbc.Driver
    initialization-mode: always

  messages:
    basename: messages
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 100KB

path:
  image: Path for Production environment

github:
  callbackUrl: http://localhost:8080/github/callback